name: BuildingWandsPlus
version: 2.0.5
main: com.optimusprimerdc.buildingwandsplus.BuildingWandsPlus
api-version: 1.21.1
author: OptimusPrimeRDC
softdepend: [WorldGuard, Towny]
commands:
  wands:
    description: Give a wand to a player, reload the plugin configuration, or undo the last operation
    usage: /wands <give|reload|undo> [playername]
    permission: buildingwandsplus.command.wands
permissions:
  buildingwandsplus.command.wands:
    description: Allows the player to use the /wands command
    default: op
  buildingwandsplus.command.reload:
    description: Allows the player to reload the plugin configuration
    default: op
  buildingwandsplus.override:
    description: Allows the player to bypass WorldGuard protection (WARNING!!!!!! This is dangerous)
    default: op
  buildingwandsplus.command.admin:
    description: Allows the player to get update notifications and download the latest version of the plugin
    default: op